"""fix fk

Revision ID: bfd964817ccf
Revises: e98188142bee
Create Date: 2024-01-27 10:34:28.479259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd964817ccf'
down_revision = 'e98188142bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('votes_publication_id_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'publications', ['publication_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_publication_id_fkey', 'votes', 'users', ['publication_id'], ['id'])
    # ### end Alembic commands ###
